sudo: required
dist: trusty

language: node_js
node_js:
  - '8.11'

install:
  - npm install

script:
  - echo "Triggered through push!"
  - npm run lint
  - npm run test-single-run
  - npm run build
  - echo "Tasks finished"

  # after_success:
#   here perform after operations, like ftp upload of the build etc...
